// GENERATED FILE -- do not edit.
//
// Source of truth is levels/*.json; regenerate with `node tools/levels.mjs --sync`.
// These are the pre-built levels: authored specs rather than parsed prose, so
// they are exactly what was tuned and audited, seed included.

export const PREBUILT = [
  {
    label: "PROVING GROUND",
    blurb: "One of everything, one per stretch, slow enough to read: sliding walls, crushers, pinwheels, crossbars, rings, two bulkheads you can open by shooting their panels instead of climbing, and a surface that is never safe.",
    spec: {
      "name": "PROVING GROUND",
      "seed": 1701,
      "speed": {
        "start": 230,
        "end": 290
      },
      "finale": "port",
      "armedPort": false,
      "music": "bumblebee",
      "boss": null,
      "sections": [
        {
          "name": "open air",
          "length": 2200,
          "width": 112,
          "depth": 92,
          "curviness": 0.1,
          "snaking": 0,
          "hilliness": 0.15,
          "roughness": 0.3,
          "obstacles": 0.14,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.55
        },
        {
          "name": "sliding walls",
          "length": 2200,
          "width": 104,
          "depth": 100,
          "curviness": 0.16,
          "snaking": 0,
          "hilliness": 0.2,
          "roughness": 0.34,
          "obstacles": 0.5,
          "kinds": [
            "slider"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.1,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.5
        },
        {
          "name": "the crushers",
          "length": 2200,
          "width": 100,
          "depth": 108,
          "curviness": 0.2,
          "snaking": 0,
          "hilliness": 0.24,
          "roughness": 0.38,
          "obstacles": 0.5,
          "kinds": [
            "press"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.14,
          "drones": 0.22,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.44
        },
        {
          "name": "pinwheels",
          "length": 2200,
          "width": 98,
          "depth": 112,
          "curviness": 0.24,
          "snaking": 0,
          "hilliness": 0.26,
          "roughness": 0.4,
          "obstacles": 0.5,
          "kinds": [
            "pinwheel"
          ],
          "turrets": 0.25,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.18,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.36
        },
        {
          "name": "crossbars",
          "length": 2200,
          "width": 94,
          "depth": 114,
          "curviness": 0.28,
          "snaking": 0,
          "hilliness": 0.28,
          "roughness": 0.42,
          "obstacles": 0.5,
          "kinds": [
            "cross"
          ],
          "turrets": 0.28,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.28
        },
        {
          "name": "the rings",
          "length": 2200,
          "width": 90,
          "depth": 118,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.44,
          "obstacles": 0.5,
          "kinds": [
            "ring"
          ],
          "turrets": 0.31,
          "gatlings": 0.31,
          "batteries": 0.24,
          "wallguns": 0.22,
          "drones": 0.22,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.2
        },
        {
          "name": "the gates",
          "length": 2200,
          "width": 92,
          "depth": 118,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.44,
          "obstacles": 0.5,
          "kinds": [
            "gate"
          ],
          "turrets": 0.31,
          "gatlings": 0.31,
          "batteries": 0.24,
          "wallguns": 0.22,
          "drones": 0.22,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.16
        },
        {
          "name": "first bulkhead",
          "length": 2200,
          "width": 86,
          "depth": 122,
          "curviness": 0.26,
          "snaking": 0,
          "hilliness": 0.26,
          "roughness": 0.42,
          "obstacles": 0.2,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.49,
          "gatlings": 0.51,
          "batteries": 0.4,
          "wallguns": 0.16,
          "drones": 0.2,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.14
        },
        {
          "name": "the defended surface",
          "length": 2200,
          "width": 82,
          "depth": 126,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.4,
          "kinds": [
            "stack"
          ],
          "turrets": 0.77,
          "gatlings": 0.85,
          "batteries": 0.72,
          "wallguns": 0.3,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.08
        },
        {
          "name": "second bulkhead",
          "length": 2200,
          "width": 80,
          "depth": 128,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.2,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.7,
          "gatlings": 0.77,
          "batteries": 0.64,
          "wallguns": 0.2,
          "drones": 0.24,
          "seals": 1,
          "panels": 4,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.05
        },
        {
          "name": "run to the port",
          "length": 2200,
          "width": 80,
          "depth": 120,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.26,
          "roughness": 0.42,
          "obstacles": 0.42,
          "kinds": [
            "fang",
            "gate",
            "pinwheel"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.32,
          "wallguns": 0.28,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.02
        }
      ]
    },
  },
  {
    label: "SHAKEDOWN",
    blurb: "The first minute of this game. It opens almost empty and wide on purpose: nothing shoots at you down in the trench until you have flown a while, the rim is watched from the start, and the one bulkhead waits until you have already learned to climb.",
    spec: {
      "name": "SHAKEDOWN",
      "seed": 4211,
      "speed": {
        "start": 230,
        "end": 300
      },
      "finale": "port",
      "armedPort": false,
      "music": "bumblebee",
      "boss": null,
      "sections": [
        {
          "name": "open approach",
          "length": 3000,
          "width": 112,
          "depth": 88,
          "curviness": 0.08,
          "snaking": 0,
          "hilliness": 0.15,
          "roughness": 0.3,
          "obstacles": 0.1,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0,
          "drones": 0.15,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.5
        },
        {
          "name": "first columns",
          "length": 3000,
          "width": 100,
          "depth": 96,
          "curviness": 0.18,
          "snaking": 0,
          "hilliness": 0.22,
          "roughness": 0.36,
          "obstacles": 0.22,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0,
          "drones": 0.25,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.5
        },
        {
          "name": "the bend",
          "length": 3000,
          "width": 88,
          "depth": 108,
          "curviness": 0.38,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.42,
          "obstacles": 0.3,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.25,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.12,
          "drones": 0.28,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.51
        },
        {
          "name": "hanging fangs",
          "length": 3000,
          "width": 80,
          "depth": 116,
          "curviness": 0.42,
          "snaking": 0,
          "hilliness": 0.35,
          "roughness": 0.46,
          "obstacles": 0.38,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.35,
          "gatlings": 0.31,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.3,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.51
        },
        {
          "name": "one bulkhead",
          "length": 3000,
          "width": 74,
          "depth": 124,
          "curviness": 0.36,
          "snaking": 0,
          "hilliness": 0.32,
          "roughness": 0.45,
          "obstacles": 0.3,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.7,
          "gatlings": 0.51,
          "batteries": 0.4,
          "wallguns": 0.18,
          "drones": 0.25,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.52
        },
        {
          "name": "run to the port",
          "length": 3000,
          "width": 68,
          "depth": 120,
          "curviness": 0.4,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.36,
          "kinds": [
            "fang",
            "gate"
          ],
          "turrets": 0.42,
          "gatlings": 0.37,
          "batteries": 0.24,
          "wallguns": 0.3,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.52
        }
      ]
    },
  },
  {
    label: "BULKHEAD RUN",
    blurb: "The brief this game was built to. A wide mouth that narrows for the rest of your life, sealed three times, with the surface guns waiting every time you are forced over the rim.",
    spec: {
      "name": "BULKHEAD RUN",
      "seed": 90210,
      "speed": {
        "start": 260,
        "end": 430
      },
      "finale": "port",
      "armedPort": false,
      "music": "bumblebee",
      "boss": null,
      "sections": [
        {
          "name": "wide mouth",
          "length": 4350,
          "width": 118,
          "depth": 110,
          "curviness": 0.12,
          "snaking": 0,
          "hilliness": 0.2,
          "roughness": 0.35,
          "obstacles": 0.12,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.66
        },
        {
          "name": "first narrowing",
          "length": 4350,
          "width": 96,
          "depth": 128,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.28,
          "roughness": 0.45,
          "obstacles": 0.26,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.12,
          "drones": 0.25,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.655
        },
        {
          "name": "the narrows",
          "length": 4350,
          "width": 74,
          "depth": 145,
          "curviness": 0.5,
          "snaking": 0,
          "hilliness": 0.4,
          "roughness": 0.52,
          "obstacles": 0.4,
          "kinds": [
            "pylon",
            "fang",
            "gate"
          ],
          "turrets": 0.42,
          "gatlings": 0.48,
          "batteries": 0.35,
          "wallguns": 0.3,
          "drones": 0.3,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.65
        },
        {
          "name": "deep water",
          "length": 4350,
          "width": 62,
          "depth": 158,
          "curviness": 0.62,
          "snaking": 0,
          "hilliness": 0.45,
          "roughness": 0.58,
          "obstacles": 0.48,
          "kinds": [
            "fang",
            "gate",
            "slider"
          ],
          "turrets": 0.63,
          "gatlings": 0.68,
          "batteries": 0.56,
          "wallguns": 0.4,
          "drones": 0.28,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.645
        },
        {
          "name": "sealed deep",
          "length": 4350,
          "width": 54,
          "depth": 168,
          "curviness": 0.66,
          "snaking": 0,
          "hilliness": 0.48,
          "roughness": 0.6,
          "obstacles": 0.44,
          "kinds": [
            "fang",
            "gate",
            "ring"
          ],
          "turrets": 0.84,
          "gatlings": 0.94,
          "batteries": 0.88,
          "wallguns": 0.35,
          "drones": 0.24,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.64
        },
        {
          "name": "the choke",
          "length": 4350,
          "width": 44,
          "depth": 156,
          "curviness": 0.5,
          "snaking": 0,
          "hilliness": 0.35,
          "roughness": 0.52,
          "obstacles": 0.5,
          "kinds": [
            "ring",
            "gate",
            "press"
          ],
          "turrets": 0.49,
          "gatlings": 0.77,
          "batteries": 0.64,
          "wallguns": 0.45,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.635
        },
        {
          "name": "last light",
          "length": 4350,
          "width": 40,
          "depth": 150,
          "curviness": 0.42,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.48,
          "obstacles": 0.45,
          "kinds": [
            "ring",
            "pinwheel"
          ],
          "turrets": 0.42,
          "gatlings": 0.59,
          "batteries": 0.48,
          "wallguns": 0.4,
          "drones": 0.18,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.63
        }
      ]
    },
  },
  {
    label: "REACTOR",
    blurb: "Everything at once, on fire, at speed. It still starts gently -- then staggered slabs, an iris chain, four bulkheads, and a core that will not open until you hold the lock.",
    spec: {
      "name": "REACTOR",
      "seed": 66613,
      "speed": {
        "start": 300,
        "end": 500
      },
      "finale": "port",
      "armedPort": false,
      "music": "fire",
      "boss": null,
      "sections": [
        {
          "name": "the descent",
          "length": 5200,
          "width": 100,
          "depth": 130,
          "curviness": 0.15,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.5,
          "obstacles": 0.14,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0,
          "drones": 0.25,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.02
        },
        {
          "name": "into the red",
          "length": 5200,
          "width": 82,
          "depth": 150,
          "curviness": 0.35,
          "snaking": 0,
          "hilliness": 0.45,
          "roughness": 0.6,
          "obstacles": 0.3,
          "kinds": [
            "pylon",
            "stack",
            "slider"
          ],
          "turrets": 0.28,
          "gatlings": 0.34,
          "batteries": 0.24,
          "wallguns": 0.2,
          "drones": 0.3,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.02
        },
        {
          "name": "slab field",
          "length": 5200,
          "width": 66,
          "depth": 168,
          "curviness": 0.5,
          "snaking": 0,
          "hilliness": 0.55,
          "roughness": 0.65,
          "obstacles": 0.45,
          "kinds": [
            "stack",
            "pylon"
          ],
          "turrets": 0.42,
          "gatlings": 0.59,
          "batteries": 0.48,
          "wallguns": 0.35,
          "drones": 0.35,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.01
        },
        {
          "name": "gauntlet",
          "length": 5200,
          "width": 56,
          "depth": 180,
          "curviness": 0.65,
          "snaking": 0,
          "hilliness": 0.55,
          "roughness": 0.65,
          "obstacles": 0.55,
          "kinds": [
            "stack",
            "gate",
            "press"
          ],
          "turrets": 0.63,
          "gatlings": 0.85,
          "batteries": 0.72,
          "wallguns": 0.45,
          "drones": 0.35,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.01
        },
        {
          "name": "sealed core",
          "length": 5200,
          "width": 50,
          "depth": 192,
          "curviness": 0.7,
          "snaking": 0,
          "hilliness": 0.5,
          "roughness": 0.6,
          "obstacles": 0.5,
          "kinds": [
            "gate",
            "fang",
            "ring"
          ],
          "turrets": 0.87,
          "gatlings": 1,
          "batteries": 1,
          "wallguns": 0.42,
          "drones": 0.3,
          "seals": 2,
          "panels": 4,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.01
        },
        {
          "name": "iris chain",
          "length": 5200,
          "width": 44,
          "depth": 196,
          "curviness": 0.75,
          "snaking": 0,
          "hilliness": 0.45,
          "roughness": 0.55,
          "obstacles": 0.55,
          "kinds": [
            "ring",
            "gate",
            "pinwheel"
          ],
          "turrets": 0.77,
          "gatlings": 1,
          "batteries": 0.96,
          "wallguns": 0.5,
          "drones": 0.28,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.04
        },
        {
          "name": "last bulkhead",
          "length": 5200,
          "width": 40,
          "depth": 190,
          "curviness": 0.6,
          "snaking": 0,
          "hilliness": 0.4,
          "roughness": 0.55,
          "obstacles": 0.5,
          "kinds": [
            "ring",
            "cross"
          ],
          "turrets": 0.84,
          "gatlings": 1,
          "batteries": 1,
          "wallguns": 0.5,
          "drones": 0.26,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.03
        },
        {
          "name": "core approach",
          "length": 5200,
          "width": 36,
          "depth": 180,
          "curviness": 0.42,
          "snaking": 0,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.42,
          "kinds": [
            "ring"
          ],
          "turrets": 0.56,
          "gatlings": 1,
          "batteries": 0.8,
          "wallguns": 0.5,
          "drones": 0.22,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0
        }
      ]
    },
  },
  {
    label: "GAUNTLET",
    blurb: "Very fast, narrow and hilly the whole way, staggered slabs and gates, wall guns everywhere, sealed four times, glowing red. The description that built it is in the README; this is what it compiled to.",
    spec: {
      "name": "GAUNTLET",
      "seed": 1337,
      "speed": {
        "start": 370,
        "end": 540
      },
      "finale": "port",
      "armedPort": false,
      "music": "bumblebee",
      "boss": null,
      "sections": [
        {
          "name": "the drop",
          "length": 6000,
          "width": 82,
          "depth": 120,
          "curviness": 0.3,
          "snaking": 0,
          "hilliness": 0.6,
          "roughness": 0.55,
          "obstacles": 0.34,
          "kinds": [
            "stack",
            "gate"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.34,
          "wallguns": 0.55,
          "drones": 0.28,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.15
        },
        {
          "name": "first seal",
          "length": 6000,
          "width": 72,
          "depth": 132,
          "curviness": 0.4,
          "snaking": 0,
          "hilliness": 0.78,
          "roughness": 0.55,
          "obstacles": 0.38,
          "kinds": [
            "stack",
            "gate"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.34,
          "wallguns": 0.55,
          "drones": 0.28,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.15
        },
        {
          "name": "slab run",
          "length": 6000,
          "width": 64,
          "depth": 144,
          "curviness": 0.4,
          "snaking": 0,
          "hilliness": 0.78,
          "roughness": 0.55,
          "obstacles": 0.5,
          "kinds": [
            "stack"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.34,
          "wallguns": 0.55,
          "drones": 0.28,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.14
        },
        {
          "name": "the squeeze",
          "length": 6000,
          "width": 56,
          "depth": 152,
          "curviness": 0.4,
          "snaking": 0,
          "hilliness": 0.78,
          "roughness": 0.55,
          "obstacles": 0.5,
          "kinds": [
            "stack",
            "gate"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.34,
          "wallguns": 0.55,
          "drones": 0.28,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.14
        },
        {
          "name": "last seal",
          "length": 6000,
          "width": 52,
          "depth": 150,
          "curviness": 0.4,
          "snaking": 0,
          "hilliness": 0.78,
          "roughness": 0.55,
          "obstacles": 0.46,
          "kinds": [
            "stack",
            "gate"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.34,
          "wallguns": 0.65,
          "drones": 0.28,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.13
        },
        {
          "name": "run to the core",
          "length": 6000,
          "width": 50,
          "depth": 140,
          "curviness": 0.4,
          "snaking": 0,
          "hilliness": 0.78,
          "roughness": 0.55,
          "obstacles": 0.44,
          "kinds": [
            "gate",
            "stack"
          ],
          "turrets": 0.42,
          "gatlings": 0.42,
          "batteries": 0.34,
          "wallguns": 0.55,
          "drones": 0.28,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.13
        }
      ]
    },
  },
  {
    label: "THE ESSES",
    blurb: "A river with room to think. Every bend is followed by a straight to line up on and then a run of slits, each run tighter than the last. Roll onto an edge to make them comfortable -- turbo gates down the straights, and the canyon is wide enough to see round its own bends.",
    spec: {
      "name": "THE ESSES",
      "seed": 2115,
      "speed": {
        "start": 240,
        "end": 400
      },
      "finale": "port",
      "armedPort": false,
      "music": "water",
      "boss": null,
      "sections": [
        {
          "name": "open water",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.5,
          "snaking": 0.3,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.12,
          "kinds": [
            "pylon",
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.53
        },
        {
          "name": "first bend",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.9,
          "snaking": 0.55,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.2,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.52
        },
        {
          "name": "line up",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.12,
          "snaking": 0.02,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.42,
          "kinds": [
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.5,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.51
        },
        {
          "name": "the wide slits",
          "length": 2600,
          "width": 120,
          "depth": 118,
          "curviness": 0.12,
          "snaking": 0.02,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.9,
          "kinds": [
            "slot",
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.15,
          "seals": 0,
          "panels": 2,
          "slotgap": 14,
          "ringrate": 0.2,
          "hue": 0.5
        },
        {
          "name": "second bend",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.9,
          "snaking": 0.6,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.24,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.49
        },
        {
          "name": "line up again",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.12,
          "snaking": 0.02,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.42,
          "kinds": [
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.55,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.48
        },
        {
          "name": "narrower",
          "length": 2600,
          "width": 120,
          "depth": 118,
          "curviness": 0.12,
          "snaking": 0.02,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.9,
          "kinds": [
            "slot",
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.15,
          "seals": 0,
          "panels": 2,
          "slotgap": 11,
          "ringrate": 0.2,
          "hue": 0.49
        },
        {
          "name": "the hard bend",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.9,
          "snaking": 0.68,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.28,
          "kinds": [
            "pylon",
            "fang"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.5
        },
        {
          "name": "last runway",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.12,
          "snaking": 0.02,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.42,
          "kinds": [
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.6,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.51
        },
        {
          "name": "on edge",
          "length": 2600,
          "width": 120,
          "depth": 118,
          "curviness": 0.12,
          "snaking": 0.02,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.9,
          "kinds": [
            "slot",
            "boostgate"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.15,
          "seals": 0,
          "panels": 2,
          "slotgap": 8,
          "ringrate": 0.2,
          "hue": 0.52
        },
        {
          "name": "run to the port",
          "length": 2200,
          "width": 120,
          "depth": 118,
          "curviness": 0.5,
          "snaking": 0.3,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.42,
          "kinds": [
            "ring"
          ],
          "turrets": 0.22,
          "gatlings": 0.26,
          "batteries": 0.2,
          "wallguns": 0.2,
          "drones": 0.24,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.53
        }
      ]
    },
  },
  {
    label: "CANOPY RUN",
    blurb: "A district the growth took back. Vine rings hang across the water channels and fire slow walls of light, the old windmills still turn where the wind finds them, and the deeper you go the closer the thicket leans in. It opens up once, near the end, so you can breathe before the roots.",
    spec: {
      "name": "CANOPY RUN",
      "seed": 4242,
      "speed": {
        "start": 250,
        "end": 410
      },
      "finale": "port",
      "armedPort": false,
      "music": "overgrowth",
      "boss": null,
      "sections": [
        {
          "name": "the eaves",
          "length": 2400,
          "width": 118,
          "depth": 116,
          "curviness": 0.4,
          "snaking": 0.15,
          "hilliness": 0.35,
          "roughness": 0.5,
          "obstacles": 0.14,
          "kinds": [
            "pylon",
            "boostgate"
          ],
          "turrets": 0.2,
          "gatlings": 0.2,
          "batteries": 0.12,
          "wallguns": 0.15,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.3
        },
        {
          "name": "vine rows",
          "length": 2600,
          "width": 100,
          "depth": 118,
          "curviness": 0.5,
          "snaking": 0.25,
          "hilliness": 0.3,
          "roughness": 0.5,
          "obstacles": 0.34,
          "kinds": [
            "ring",
            "ring",
            "pylon",
            "diamond"
          ],
          "turrets": 0.28,
          "gatlings": 0.25,
          "batteries": 0.18,
          "wallguns": 0.25,
          "drones": 0.3,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.3,
          "hue": 0.31
        },
        {
          "name": "the windmills",
          "length": 2800,
          "width": 92,
          "depth": 122,
          "curviness": 0.45,
          "snaking": 0.2,
          "hilliness": 0.4,
          "roughness": 0.55,
          "obstacles": 0.4,
          "kinds": [
            "pinwheel",
            "pinwheel",
            "gate"
          ],
          "turrets": 0.3,
          "gatlings": 0.3,
          "batteries": 0.2,
          "wallguns": 0.3,
          "drones": 0.3,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.32
        },
        {
          "name": "thicket",
          "length": 2600,
          "width": 80,
          "depth": 114,
          "curviness": 0.6,
          "snaking": 0.35,
          "hilliness": 0.35,
          "roughness": 0.6,
          "obstacles": 0.46,
          "kinds": [
            "gate",
            "fang",
            "ring",
            "diamond"
          ],
          "turrets": 0.35,
          "gatlings": 0.3,
          "batteries": 0.25,
          "wallguns": 0.4,
          "drones": 0.4,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.24,
          "hue": 0.33
        },
        {
          "name": "the clearing",
          "length": 2000,
          "width": 112,
          "depth": 120,
          "curviness": 0.35,
          "snaking": 0.1,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.12,
          "kinds": [
            "pylon",
            "boostgate"
          ],
          "turrets": 0.25,
          "gatlings": 0.3,
          "batteries": 0.25,
          "wallguns": 0.15,
          "drones": 0.25,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.34
        },
        {
          "name": "deep growth",
          "length": 2800,
          "width": 78,
          "depth": 116,
          "curviness": 0.65,
          "snaking": 0.4,
          "hilliness": 0.35,
          "roughness": 0.6,
          "obstacles": 0.5,
          "kinds": [
            "ring",
            "pinwheel",
            "gate",
            "diamond"
          ],
          "turrets": 0.4,
          "gatlings": 0.35,
          "batteries": 0.3,
          "wallguns": 0.45,
          "drones": 0.45,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.35
        },
        {
          "name": "the roots",
          "length": 2600,
          "width": 68,
          "depth": 110,
          "curviness": 0.6,
          "snaking": 0.35,
          "hilliness": 0.4,
          "roughness": 0.65,
          "obstacles": 0.46,
          "kinds": [
            "fang",
            "cross",
            "ring"
          ],
          "turrets": 0.4,
          "gatlings": 0.4,
          "batteries": 0.3,
          "wallguns": 0.5,
          "drones": 0.4,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.22,
          "hue": 0.36
        },
        {
          "name": "canopy break",
          "length": 2200,
          "width": 88,
          "depth": 118,
          "curviness": 0.45,
          "snaking": 0.2,
          "hilliness": 0.3,
          "roughness": 0.5,
          "obstacles": 0.28,
          "kinds": [
            "pylon",
            "gate",
            "boostgate"
          ],
          "turrets": 0.45,
          "gatlings": 0.45,
          "batteries": 0.35,
          "wallguns": 0.35,
          "drones": 0.45,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.36
        }
      ]
    },
  },
  {
    label: "DEAD AIR",
    blurb: "A district with nothing left in it, which is not the same as nothing. Long silent flats where the trench is barely a trench and the static ticks -- then a pocket of them, all at once, and silence again. The quiet is the level. Do not trust it.",
    spec: {
      "name": "DEAD AIR",
      "seed": 9009,
      "speed": {
        "start": 270,
        "end": 440
      },
      "finale": "port",
      "armedPort": false,
      "music": "void",
      "boss": null,
      "sections": [
        {
          "name": "flatline",
          "length": 3500,
          "width": 130,
          "depth": 62,
          "curviness": 0.25,
          "snaking": 0.05,
          "hilliness": 0.15,
          "roughness": 0.3,
          "obstacles": 0.06,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.06,
          "gatlings": 0.05,
          "batteries": 0.05,
          "wallguns": 0.05,
          "drones": 0.1,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.9
        },
        {
          "name": "first pocket",
          "length": 1600,
          "width": 100,
          "depth": 78,
          "curviness": 0.35,
          "snaking": 0.15,
          "hilliness": 0.25,
          "roughness": 0.4,
          "obstacles": 0.2,
          "kinds": [
            "fang",
            "cross"
          ],
          "turrets": 0.5,
          "gatlings": 0.45,
          "batteries": 0.5,
          "wallguns": 0.3,
          "drones": 0.7,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.91
        },
        {
          "name": "static",
          "length": 3500,
          "width": 126,
          "depth": 58,
          "curviness": 0.2,
          "snaking": 0.05,
          "hilliness": 0.15,
          "roughness": 0.3,
          "obstacles": 0.08,
          "kinds": [
            "pylon",
            "diamond"
          ],
          "turrets": 0.08,
          "gatlings": 0.06,
          "batteries": 0.05,
          "wallguns": 0.05,
          "drones": 0.12,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.91
        },
        {
          "name": "second pocket",
          "length": 1800,
          "width": 92,
          "depth": 84,
          "curviness": 0.4,
          "snaking": 0.2,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.26,
          "kinds": [
            "gate",
            "slider",
            "fang"
          ],
          "turrets": 0.55,
          "gatlings": 0.5,
          "batteries": 0.55,
          "wallguns": 0.35,
          "drones": 0.75,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.92
        },
        {
          "name": "the hollow",
          "length": 3500,
          "width": 132,
          "depth": 56,
          "curviness": 0.2,
          "snaking": 0.05,
          "hilliness": 0.1,
          "roughness": 0.25,
          "obstacles": 0.06,
          "kinds": [
            "pylon",
            "boostgate"
          ],
          "turrets": 0.06,
          "gatlings": 0.05,
          "batteries": 0.05,
          "wallguns": 0.05,
          "drones": 0.1,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.92
        },
        {
          "name": "third pocket",
          "length": 2000,
          "width": 88,
          "depth": 88,
          "curviness": 0.45,
          "snaking": 0.25,
          "hilliness": 0.3,
          "roughness": 0.5,
          "obstacles": 0.3,
          "kinds": [
            "cross",
            "gate",
            "fang",
            "diamond"
          ],
          "turrets": 0.6,
          "gatlings": 0.55,
          "batteries": 0.6,
          "wallguns": 0.4,
          "drones": 0.8,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.93
        },
        {
          "name": "the last flat",
          "length": 4100,
          "width": 124,
          "depth": 60,
          "curviness": 0.25,
          "snaking": 0.08,
          "hilliness": 0.15,
          "roughness": 0.3,
          "obstacles": 0.1,
          "kinds": [
            "pylon"
          ],
          "turrets": 0.15,
          "gatlings": 0.12,
          "batteries": 0.15,
          "wallguns": 0.08,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.94
        }
      ]
    },
  },
  {
    label: "NEON DISTRICT",
    blurb: "The power grid at night. Wide avenues of light that keep narrowing into the wires: coil rings that fire fast, sliding switchgear, and more drones than anywhere else in the game. The diamond gates are here -- fly through them and the special charges past its base. Somewhere in the dark stretch there is a prism.",
    spec: {
      "name": "NEON DISTRICT",
      "seed": 7013,
      "speed": {
        "start": 260,
        "end": 430
      },
      "finale": "port",
      "armedPort": false,
      "music": "neon",
      "boss": {
        "kind": "marionette",
        "name": "MARIONETTE",
        "hp": 90,
        "weapon": "arc",
        "weakTo": "saw",
        "arena": "surface"
      },
      "sections": [
        {
          "name": "the on-ramp",
          "length": 2400,
          "width": 118,
          "depth": 122,
          "curviness": 0.35,
          "snaking": 0.1,
          "hilliness": 0.25,
          "roughness": 0.4,
          "obstacles": 0.14,
          "kinds": [
            "pylon",
            "boostgate",
            "diamond"
          ],
          "turrets": 0.2,
          "gatlings": 0.2,
          "batteries": 0.15,
          "wallguns": 0.15,
          "drones": 0.35,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.74
        },
        {
          "name": "substation",
          "length": 2600,
          "width": 100,
          "depth": 122,
          "curviness": 0.5,
          "snaking": 0.2,
          "hilliness": 0.3,
          "roughness": 0.5,
          "obstacles": 0.3,
          "kinds": [
            "ring",
            "stack",
            "diamond"
          ],
          "turrets": 0.3,
          "gatlings": 0.3,
          "batteries": 0.2,
          "wallguns": 0.3,
          "drones": 0.45,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.14,
          "hue": 0.76
        },
        {
          "name": "switchgear",
          "length": 2600,
          "width": 88,
          "depth": 118,
          "curviness": 0.55,
          "snaking": 0.25,
          "hilliness": 0.35,
          "roughness": 0.5,
          "obstacles": 0.38,
          "kinds": [
            "slider",
            "cross",
            "gate"
          ],
          "turrets": 0.35,
          "gatlings": 0.3,
          "batteries": 0.25,
          "wallguns": 0.4,
          "drones": 0.5,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.78
        },
        {
          "name": "the coil run",
          "length": 2800,
          "width": 80,
          "depth": 118,
          "curviness": 0.6,
          "snaking": 0.3,
          "hilliness": 0.3,
          "roughness": 0.5,
          "obstacles": 0.42,
          "kinds": [
            "ring",
            "ring",
            "slider",
            "diamond"
          ],
          "turrets": 0.35,
          "gatlings": 0.35,
          "batteries": 0.25,
          "wallguns": 0.4,
          "drones": 0.55,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.1,
          "hue": 0.79
        },
        {
          "name": "breaker row",
          "length": 2600,
          "width": 84,
          "depth": 124,
          "curviness": 0.5,
          "snaking": 0.2,
          "hilliness": 0.4,
          "roughness": 0.55,
          "obstacles": 0.4,
          "kinds": [
            "gate",
            "cross",
            "boostgate"
          ],
          "turrets": 0.4,
          "gatlings": 0.35,
          "batteries": 0.3,
          "wallguns": 0.5,
          "drones": 0.5,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.8
        },
        {
          "name": "the dark stretch",
          "length": 2400,
          "width": 96,
          "depth": 130,
          "curviness": 0.4,
          "snaking": 0.15,
          "hilliness": 0.25,
          "roughness": 0.4,
          "obstacles": 0.14,
          "kinds": [
            "prism"
          ],
          "turrets": 0.5,
          "gatlings": 0.45,
          "batteries": 0.4,
          "wallguns": 0.2,
          "drones": 0.65,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.72
        },
        {
          "name": "live wires",
          "length": 2800,
          "width": 76,
          "depth": 116,
          "curviness": 0.65,
          "snaking": 0.35,
          "hilliness": 0.35,
          "roughness": 0.55,
          "obstacles": 0.46,
          "kinds": [
            "ring",
            "slider",
            "slot",
            "diamond"
          ],
          "turrets": 0.4,
          "gatlings": 0.4,
          "batteries": 0.3,
          "wallguns": 0.45,
          "drones": 0.6,
          "seals": 0,
          "panels": 2,
          "slotgap": 8,
          "ringrate": 0.09,
          "hue": 0.82
        },
        {
          "name": "grid heart",
          "length": 2600,
          "width": 72,
          "depth": 114,
          "curviness": 0.6,
          "snaking": 0.3,
          "hilliness": 0.4,
          "roughness": 0.55,
          "obstacles": 0.44,
          "kinds": [
            "ring",
            "cross",
            "gate",
            "diamond"
          ],
          "turrets": 0.45,
          "gatlings": 0.45,
          "batteries": 0.35,
          "wallguns": 0.5,
          "drones": 0.6,
          "seals": 1,
          "panels": 3,
          "slotgap": 4,
          "ringrate": 0.09,
          "hue": 0.84
        },
        {
          "name": "the last avenue",
          "length": 2400,
          "width": 82,
          "depth": 118,
          "curviness": 0.45,
          "snaking": 0.2,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.3,
          "kinds": [
            "stack",
            "boostgate",
            "diamond"
          ],
          "turrets": 0.5,
          "gatlings": 0.5,
          "batteries": 0.4,
          "wallguns": 0.4,
          "drones": 0.55,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.2,
          "hue": 0.86
        }
      ]
    },
  },
  {
    label: "THE SHEAR",
    blurb: "The frozen intake. Everything here is a blade: sheets of ice grown across the channel with one slot cut through, each run of them tighter than the last, and the presses still cycling under the frost. Knife-edge country -- come in level, leave on edge.",
    spec: {
      "name": "THE SHEAR",
      "seed": 6103,
      "speed": {
        "start": 260,
        "end": 420
      },
      "finale": "port",
      "armedPort": false,
      "music": "glacier",
      "boss": null,
      "sections": [
        {
          "name": "the intake",
          "length": 2400,
          "width": 120,
          "depth": 112,
          "curviness": 0.35,
          "snaking": 0.1,
          "hilliness": 0.25,
          "roughness": 0.35,
          "obstacles": 0.12,
          "kinds": [
            "pylon",
            "boostgate"
          ],
          "turrets": 0.2,
          "gatlings": 0.18,
          "batteries": 0.12,
          "wallguns": 0.15,
          "drones": 0.15,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.56
        },
        {
          "name": "first shear",
          "length": 2600,
          "width": 100,
          "depth": 116,
          "curviness": 0.4,
          "snaking": 0.15,
          "hilliness": 0.3,
          "roughness": 0.4,
          "obstacles": 0.36,
          "kinds": [
            "slot",
            "pylon",
            "diamond"
          ],
          "turrets": 0.25,
          "gatlings": 0.22,
          "batteries": 0.15,
          "wallguns": 0.25,
          "drones": 0.2,
          "seals": 0,
          "panels": 2,
          "slotgap": 10,
          "ringrate": 0.25,
          "hue": 0.57
        },
        {
          "name": "the crevasse",
          "length": 3000,
          "width": 78,
          "depth": 124,
          "curviness": 0.65,
          "snaking": 0.45,
          "hilliness": 0.35,
          "roughness": 0.5,
          "obstacles": 0.3,
          "kinds": [
            "fang",
            "slider",
            "gate"
          ],
          "turrets": 0.3,
          "gatlings": 0.25,
          "batteries": 0.2,
          "wallguns": 0.35,
          "drones": 0.25,
          "seals": 0,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.57
        },
        {
          "name": "the presses",
          "length": 2600,
          "width": 88,
          "depth": 118,
          "curviness": 0.4,
          "snaking": 0.15,
          "hilliness": 0.4,
          "roughness": 0.5,
          "obstacles": 0.42,
          "kinds": [
            "press",
            "press",
            "gate",
            "diamond"
          ],
          "turrets": 0.3,
          "gatlings": 0.3,
          "batteries": 0.2,
          "wallguns": 0.35,
          "drones": 0.25,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.58
        },
        {
          "name": "shear field",
          "length": 3200,
          "width": 84,
          "depth": 116,
          "curviness": 0.45,
          "snaking": 0.2,
          "hilliness": 0.3,
          "roughness": 0.45,
          "obstacles": 0.44,
          "kinds": [
            "slot",
            "slot",
            "pylon"
          ],
          "turrets": 0.35,
          "gatlings": 0.3,
          "batteries": 0.25,
          "wallguns": 0.35,
          "drones": 0.3,
          "seals": 0,
          "panels": 2,
          "slotgap": 8,
          "ringrate": 0.25,
          "hue": 0.59
        },
        {
          "name": "blue depth",
          "length": 2400,
          "width": 96,
          "depth": 126,
          "curviness": 0.55,
          "snaking": 0.3,
          "hilliness": 0.35,
          "roughness": 0.5,
          "obstacles": 0.3,
          "kinds": [
            "slider",
            "cross",
            "boostgate",
            "diamond"
          ],
          "turrets": 0.35,
          "gatlings": 0.35,
          "batteries": 0.3,
          "wallguns": 0.4,
          "drones": 0.3,
          "seals": 1,
          "panels": 2,
          "slotgap": 4,
          "ringrate": 0.25,
          "hue": 0.59
        },
        {
          "name": "the throat",
          "length": 3000,
          "width": 70,
          "depth": 112,
          "curviness": 0.5,
          "snaking": 0.3,
          "hilliness": 0.35,
          "roughness": 0.55,
          "obstacles": 0.46,
          "kinds": [
            "slot",
            "gate",
            "fang"
          ],
          "turrets": 0.4,
          "gatlings": 0.4,
          "batteries": 0.3,
          "wallguns": 0.45,
          "drones": 0.35,
          "seals": 0,
          "panels": 2,
          "slotgap": 7,
          "ringrate": 0.25,
          "hue": 0.6
        }
      ]
    },
  },
];
